### ISSUE TITLE
Added manual NAT.

### ISSUE THREAD

**Issue by incubenet** [CheckPoint-APIs-Team/ExportImportPolicyPackage#8]
I'm checking to add manual NAT.
But, Does not add the section?

**Comment by CheckPoint-APIs-Team** [comment]
Hi,
The original manual NAT sections are **omitted** during the process in order to avoid **merging** of rules and sections.
All rules BEFORE the automatic NAT rules are imported on TOP of new NAT rulebase under a new section "IMPORTED UPPER RULES".
All rules AFTER the automatic NAT rules are imported on BOTTOM of new NAT rulebase under a new section "IMPORTED LOWER RULES".
The original section can be added manually at the end of the process if needed.
Please see the attached images.
![exported](https://user-images.githubusercontent.com/26377847/35192345-be7cc1aa-fe98-11e7-9370-f722ad25cb58.png)
![imported](https://user-images.githubusercontent.com/26377847/35192347-c5cada82-fe98-11e7-9353-efa12192b58e.png)
